MN.PROVINCES = [
  { id: "koshi", en: "Koshi", ne: "कोशी" },
  { id: "madhesh", en: "Madhesh", ne: "मधेश" },
  { id: "bagmati", en: "Bagmati", ne: "बागमती" },
  { id: "gandaki", en: "Gandaki", ne: "गण्डकी" },
  { id: "lumbini", en: "Lumbini", ne: "लुम्बिनी" },
  { id: "karnali", en: "Karnali", ne: "कर्णाली" },
  { id: "sudurpashchim", en: "Sudurpashchim", ne: "सुदूरपश्चिम" },
];

MN.LOCATIONS = [
  { slug: "bhadrapur", en: "Bhadrapur", ne: "भद्रपुर", province: "koshi", district: "Jhapa", lat: 26.544, lon: 88.0944, elev: 90, zone: "terai", hasModel: false },
  { slug: "bhojpur", en: "Bhojpur", ne: "भोजपुर", province: "koshi", district: "Bhojpur", lat: 27.1715, lon: 87.0461, elev: 1565, zone: "hill", hasModel: false },
  { slug: "biratnagar", en: "Biratnagar", ne: "विराटनगर", province: "koshi", district: "Morang", lat: 26.4525, lon: 87.2718, elev: 72, zone: "terai", hasModel: true },
  { slug: "dhankuta", en: "Dhankuta", ne: "धनकुटा", province: "koshi", district: "Dhankuta", lat: 26.9833, lon: 87.3333, elev: 1174, zone: "hill", hasModel: false },
  { slug: "diktel", en: "Diktel", ne: "दिक्तेल", province: "koshi", district: "Khotang", lat: 27.2159, lon: 86.794, elev: 1644, zone: "hill", hasModel: false },
  { slug: "gaighat", en: "Gaighat", ne: "गाईघाट", province: "koshi", district: "Udayapur", lat: 26.7917, lon: 86.6992, elev: 162, zone: "terai", hasModel: false },
  { slug: "ilam", en: "Ilam", ne: "इलाम", province: "koshi", district: "Ilam", lat: 26.9081, lon: 87.9265, elev: 1206, zone: "hill", hasModel: true },
  { slug: "inaruwa", en: "Inaruwa", ne: "इनरुवा", province: "koshi", district: "Sunsari", lat: 26.6068, lon: 87.1478, elev: 86, zone: "terai", hasModel: false },
  { slug: "khandbari", en: "Khandbari", ne: "खाँदबारी", province: "koshi", district: "Sankhuwasabha", lat: 27.3819, lon: 87.2077, elev: 1075, zone: "hill", hasModel: false },
  { slug: "lukla", en: "Lukla", ne: "लुक्ला", province: "koshi", district: "Solukhumbu", lat: 27.6869, lon: 86.7297, elev: 2860, zone: "mountain", hasModel: true },
  { slug: "myanglung", en: "Myanglung", ne: "म्याङलुङ", province: "koshi", district: "Terhathum", lat: 27.1157, lon: 87.5418, elev: 1690, zone: "hill", hasModel: false },
  { slug: "okhaldhunga", en: "Okhaldhunga", ne: "ओखलढुङ्गा", province: "koshi", district: "Okhaldhunga", lat: 27.3113, lon: 86.5047, elev: 1740, zone: "hill", hasModel: false },
  { slug: "phidim", en: "Phidim", ne: "फिदिम", province: "koshi", district: "Panchthar", lat: 27.1456, lon: 87.767, elev: 1167, zone: "hill", hasModel: false },
  { slug: "taplejung", en: "Taplejung", ne: "ताप्लेजुङ", province: "koshi", district: "Taplejung", lat: 27.3571, lon: 87.6723, elev: 1783, zone: "hill", hasModel: false },
  { slug: "birgunj", en: "Birgunj", ne: "वीरगञ्ज", province: "madhesh", district: "Parsa", lat: 27.0104, lon: 84.8818, elev: 78, zone: "terai", hasModel: false },
  { slug: "gaur", en: "Gaur", ne: "गौर", province: "madhesh", district: "Rautahat", lat: 26.7637, lon: 85.2766, elev: 75, zone: "terai", hasModel: false },
  { slug: "jaleshwor", en: "Jaleshwor", ne: "जलेश्वर", province: "madhesh", district: "Mahottari", lat: 26.6518, lon: 85.7979, elev: 65, zone: "terai", hasModel: false },
  { slug: "janakpur", en: "Janakpur", ne: "जनकपुर", province: "madhesh", district: "Dhanusha", lat: 26.7288, lon: 85.9263, elev: 84, zone: "terai", hasModel: false },
  { slug: "kalaiya", en: "Kalaiya", ne: "कलैया", province: "madhesh", district: "Bara", lat: 27.0323, lon: 85.0026, elev: 99, zone: "terai", hasModel: false },
  { slug: "malangwa", en: "Malangwa", ne: "मलंगवा", province: "madhesh", district: "Sarlahi", lat: 26.8562, lon: 85.5603, elev: 85, zone: "terai", hasModel: false },
  { slug: "rajbiraj", en: "Rajbiraj", ne: "राजविराज", province: "madhesh", district: "Saptari", lat: 26.5397, lon: 86.748, elev: 86, zone: "terai", hasModel: false },
  { slug: "siraha", en: "Siraha", ne: "सिराहा", province: "madhesh", district: "Siraha", lat: 26.6542, lon: 86.2079, elev: 77, zone: "terai", hasModel: false },
  { slug: "bhaktapur", en: "Bhaktapur", ne: "भक्तपुर", province: "bagmati", district: "Bhaktapur", lat: 27.673, lon: 85.43, elev: 1344, zone: "hill", hasModel: false },
  { slug: "bharatpur", en: "Bharatpur", ne: "भरतपुर", province: "bagmati", district: "Chitwan", lat: 27.6803, lon: 84.4365, elev: 214, zone: "terai", hasModel: false },
  { slug: "bidur", en: "Bidur", ne: "बिदुर", province: "bagmati", district: "Nuwakot", lat: 27.9298, lon: 85.1577, elev: 614, zone: "hill", hasModel: false },
  { slug: "charikot", en: "Charikot", ne: "चरिकोट", province: "bagmati", district: "Dolakha", lat: 27.6682, lon: 86.0519, elev: 1944, zone: "hill", hasModel: false },
  { slug: "chautara", en: "Chautara", ne: "चौतारा", province: "bagmati", district: "Sindhupalchok", lat: 27.7763, lon: 85.7127, elev: 1459, zone: "hill", hasModel: false },
  { slug: "dhading-besi", en: "Dhading Besi", ne: "धादिङ बेसी", province: "bagmati", district: "Dhading", lat: 27.9125, lon: 84.8966, elev: 637, zone: "hill", hasModel: false },
  { slug: "dhulikhel", en: "Dhulikhel", ne: "धुलिखेल", province: "bagmati", district: "Kavrepalanchok", lat: 27.6221, lon: 85.5428, elev: 1477, zone: "hill", hasModel: false },
  { slug: "dhunche", en: "Dhunche", ne: "धुन्चे", province: "bagmati", district: "Rasuwa", lat: 28.1125, lon: 85.2992, elev: 1933, zone: "hill", hasModel: false },
  { slug: "hetauda", en: "Hetauda", ne: "हेटौडा", province: "bagmati", district: "Makwanpur", lat: 27.4284, lon: 85.0322, elev: 465, zone: "terai", hasModel: false },
  { slug: "kamalamai", en: "Kamalamai", ne: "कमलामाई", province: "bagmati", district: "Sindhuli", lat: 27.15, lon: 85.9, elev: 603, zone: "hill", hasModel: false },
  { slug: "kathmandu", en: "Kathmandu", ne: "काठमाडौं", province: "bagmati", district: "Kathmandu", lat: 27.7172, lon: 85.324, elev: 1400, zone: "hill", hasModel: true },
  { slug: "lalitpur", en: "Lalitpur", ne: "ललितपुर", province: "bagmati", district: "Lalitpur", lat: 27.6766, lon: 85.3142, elev: 1329, zone: "hill", hasModel: false },
  { slug: "manthali", en: "Manthali", ne: "मन्थली", province: "bagmati", district: "Ramechhap", lat: 27.3896, lon: 86.0617, elev: 501, zone: "hill", hasModel: false },
  { slug: "baglung", en: "Baglung", ne: "बागलुङ", province: "gandaki", district: "Baglung", lat: 28.2673, lon: 83.5996, elev: 968, zone: "hill", hasModel: false },
  { slug: "beni", en: "Beni", ne: "बेनी", province: "gandaki", district: "Myagdi", lat: 28.3466, lon: 83.567, elev: 854, zone: "hill", hasModel: false },
  { slug: "besisahar", en: "Besisahar", ne: "बेंसीशहर", province: "gandaki", district: "Lamjung", lat: 28.2311, lon: 84.3775, elev: 794, zone: "hill", hasModel: false },
  { slug: "chame", en: "Chame", ne: "चामे", province: "gandaki", district: "Manang", lat: 28.5537, lon: 84.251, elev: 2967, zone: "mountain", hasModel: false },
  { slug: "damauli", en: "Damauli", ne: "दमौली", province: "gandaki", district: "Tanahun", lat: 27.9776, lon: 84.2649, elev: 313, zone: "terai", hasModel: false },
  { slug: "gorkha", en: "Gorkha", ne: "गोरखा", province: "gandaki", district: "Gorkha", lat: 28.0024, lon: 84.6201, elev: 1152, zone: "hill", hasModel: false },
  { slug: "jomsom", en: "Jomsom", ne: "जोमसोम", province: "gandaki", district: "Mustang", lat: 28.7806, lon: 83.7231, elev: 2743, zone: "mountain", hasModel: true },
  { slug: "kawasoti", en: "Kawasoti", ne: "कावासोती", province: "gandaki", district: "Nawalpur", lat: 27.6252, lon: 84.1094, elev: 169, zone: "terai", hasModel: false },
  { slug: "kusma", en: "Kusma", ne: "कुश्मा", province: "gandaki", district: "Parbat", lat: 28.2227, lon: 83.6826, elev: 1011, zone: "hill", hasModel: false },
  { slug: "pokhara", en: "Pokhara", ne: "पोखरा", province: "gandaki", district: "Kaski", lat: 28.2096, lon: 83.9856, elev: 822, zone: "hill", hasModel: true },
  { slug: "putalibazar", en: "Putalibazar", ne: "पुतलीबजार", province: "gandaki", district: "Syangja", lat: 28.0955, lon: 83.8746, elev: 858, zone: "hill", hasModel: false },
  { slug: "butwal", en: "Butwal", ne: "बुटवल", province: "lumbini", district: "Rupandehi", lat: 27.6866, lon: 83.4328, elev: 188, zone: "terai", hasModel: false },
  { slug: "ghorahi", en: "Ghorahi", ne: "घोराही", province: "lumbini", district: "Dang", lat: 28.0432, lon: 82.4862, elev: 685, zone: "hill", hasModel: false },
  { slug: "gulariya", en: "Gulariya", ne: "गुलरिया", province: "lumbini", district: "Bardiya", lat: 28.2058, lon: 81.3453, elev: 147, zone: "terai", hasModel: false },
  { slug: "liwang", en: "Liwang", ne: "लिवाङ", province: "lumbini", district: "Rolpa", lat: 28.3021, lon: 82.637, elev: 1387, zone: "hill", hasModel: false },
  { slug: "nepalgunj", en: "Nepalgunj", ne: "नेपालगञ्ज", province: "lumbini", district: "Banke", lat: 28.05, lon: 81.6167, elev: 150, zone: "terai", hasModel: true },
  { slug: "pyuthan", en: "Pyuthan", ne: "प्यूठान", province: "lumbini", district: "Pyuthan", lat: 28.0887, lon: 82.8843, elev: 1308, zone: "hill", hasModel: false },
  { slug: "ramgram", en: "Ramgram", ne: "रामग्राम", province: "lumbini", district: "Parasi", lat: 27.5333, lon: 83.6667, elev: 114, zone: "terai", hasModel: false },
  { slug: "rukumkot", en: "Rukumkot", ne: "रुकुमकोट", province: "lumbini", district: "Rukum East", lat: 28.6201, lon: 82.6175, elev: 1504, zone: "hill", hasModel: false },
  { slug: "sandhikharka", en: "Sandhikharka", ne: "सन्धिखर्क", province: "lumbini", district: "Arghakhanchi", lat: 27.9751, lon: 85.1437, elev: 1269, zone: "hill", hasModel: false },
  { slug: "tamghas", en: "Tamghas", ne: "तम्घास", province: "lumbini", district: "Gulmi", lat: 28.0675, lon: 83.2463, elev: 1532, zone: "hill", hasModel: false },
  { slug: "tansen", en: "Tansen", ne: "तानसेन", province: "lumbini", district: "Palpa", lat: 27.8666, lon: 83.5459, elev: 1315, zone: "hill", hasModel: false },
  { slug: "taulihawa", en: "Taulihawa", ne: "तौलिहवा", province: "lumbini", district: "Kapilvastu", lat: 27.5456, lon: 83.0542, elev: 108, zone: "terai", hasModel: false },
  { slug: "birendranagar", en: "Birendranagar", ne: "वीरेन्द्रनगर", province: "karnali", district: "Surkhet", lat: 28.5967, lon: 81.6166, elev: 693, zone: "hill", hasModel: false },
  { slug: "dailekh", en: "Dailekh", ne: "दैलेख", province: "karnali", district: "Dailekh", lat: 28.8443, lon: 81.7101, elev: 1276, zone: "hill", hasModel: false },
  { slug: "dunai", en: "Dunai", ne: "दुनै", province: "karnali", district: "Dolpa", lat: 28.9528, lon: 82.8942, elev: 2093, zone: "hill", hasModel: false },
  { slug: "gamgadhi", en: "Gamgadhi", ne: "गमगढी", province: "karnali", district: "Mugu", lat: 29.5476, lon: 82.1577, elev: 2062, zone: "hill", hasModel: false },
  { slug: "jumla", en: "Jumla", ne: "जुम्ला", province: "karnali", district: "Jumla", lat: 29.2747, lon: 82.1838, elev: 2370, zone: "mountain", hasModel: true },
  { slug: "khalanga", en: "Khalanga", ne: "खलङ्गा", province: "karnali", district: "Jajarkot", lat: 28.698, lon: 82.1955, elev: 1204, zone: "hill", hasModel: false },
  { slug: "manma", en: "Manma", ne: "मान्मा", province: "karnali", district: "Kalikot", lat: 28.9001, lon: 81.6891, elev: 1249, zone: "hill", hasModel: false },
  { slug: "musikot", en: "Musikot", ne: "मुसिकोट", province: "karnali", district: "Rukum West", lat: 28.63, lon: 82.456, elev: 1517, zone: "hill", hasModel: false },
  { slug: "salyan", en: "Salyan", ne: "सल्यान", province: "karnali", district: "Salyan", lat: 28.3753, lon: 82.1695, elev: 1307, zone: "hill", hasModel: false },
  { slug: "simikot", en: "Simikot", ne: "सिमिकोट", province: "karnali", district: "Humla", lat: 29.9714, lon: 81.8197, elev: 2980, zone: "mountain", hasModel: false },
  { slug: "chainpur", en: "Chainpur", ne: "चैनपुर", province: "sudurpashchim", district: "Bajhang", lat: 29.5564, lon: 81.1986, elev: 1390, zone: "hill", hasModel: false },
  { slug: "dadeldhura", en: "Dadeldhura", ne: "डडेल्धुरा", province: "sudurpashchim", district: "Dadeldhura", lat: 29.2992, lon: 80.5833, elev: 1863, zone: "hill", hasModel: false },
  { slug: "darchula-khalanga", en: "Darchula Khalanga", ne: "खलङ्गा", province: "sudurpashchim", district: "Darchula", lat: 29.85, lon: 80.95, elev: 4219, zone: "mountain", hasModel: false },
  { slug: "dasharathchand", en: "Dasharathchand", ne: "दशरथचन्द", province: "sudurpashchim", district: "Baitadi", lat: 29.5711, lon: 80.4372, elev: 845, zone: "hill", hasModel: false },
  { slug: "dhangadhi", en: "Dhangadhi", ne: "धनगढी", province: "sudurpashchim", district: "Kailali", lat: 28.7046, lon: 80.5898, elev: 109, zone: "terai", hasModel: false },
  { slug: "dipayal", en: "Dipayal", ne: "दिपायल", province: "sudurpashchim", district: "Doti", lat: 29.2608, lon: 80.94, elev: 565, zone: "hill", hasModel: false },
  { slug: "mahendranagar", en: "Mahendranagar", ne: "महेन्द्रनगर", province: "sudurpashchim", district: "Kanchanpur", lat: 28.964, lon: 80.1771, elev: 218, zone: "terai", hasModel: false },
  { slug: "mangalsen", en: "Mangalsen", ne: "मङ्गलसेन", province: "sudurpashchim", district: "Achham", lat: 29.1426, lon: 81.2591, elev: 1250, zone: "hill", hasModel: false },
  { slug: "martadi", en: "Martadi", ne: "मार्तडी", province: "sudurpashchim", district: "Bajura", lat: 29.4576, lon: 81.4803, elev: 1589, zone: "hill", hasModel: false },

  { slug: "ebc", en: "Everest Base Camp", ne: "सगरमाथा आधार शिविर", province: "koshi", district: "Solukhumbu", lat: 27.9881, lon: 86.9250, elev: 5364, zone: "mountain", hasModel: false },
  { slug: "abc", en: "Annapurna Base Camp", ne: "अन्नपूर्ण आधार शिविर", province: "gandaki", district: "Kaski", lat: 28.5306, lon: 83.8779, elev: 4130, zone: "mountain", hasModel: false },
  { slug: "dharan", en: "Dharan", ne: "धरान", province: "koshi", district: "Sunsari", lat: 26.8124, lon: 87.2839, elev: 349, zone: "terai", hasModel: false },
];
